### ISSUE TITLE
Not scraping everything

### ISSUE THREAD

**Issue by B3ns0n** [npow/centris#20]
I might be missing something but it seems the scrapper does not get all the properties on the Montreal Island.
Today may 31st at 17:07 EDT, with a manual search there is 3541 properties. The scrapper returns 194 entries in the "listing.csv" file

**Comment by npow** [comment]
It's possible this code has stopped working due to API changes, or you could be rate-limited. I'm not actively maintaining this repo, but will be happy to accept PRs.
